#ifndef METABASE_TESTSWITCH_H__INCLUDED
#define METABASE_TESTSWITCH_H__INCLUDED

#ifdef COMPILE_ALL_TESTS
#define COMPILE_METABASE_TESTS
#else
#define COMPILE_METABASE_TESTS
#endif

#endif // METABASE_TESTSWITCH_H__INCLUDED
