#ifndef REFLECTOR_TESTSWITCH_H__INCLUDED
#define REFLECTOR_TESTSWITCH_H__INCLUDED

#ifdef COMPILE_ALL_TESTS
#define COMPILE_REFLECTOR_TESTS
#else
#define COMPILE_REFLECTOR_TESTS
#endif

#endif // REFLECTOR_TESTSWITCH_H__INCLUDED
